server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: 
    - application-redis.yml
    - application-apis.yml
  application:
    name: session-spring-local
