server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
---
spring:
  profiles: default
  application:
    name: session-spring-local
  redis:
    host: localhost
    port: 7000
---
spring:
  profiles: dev
  application:
    name: session-spring-dev
  redis:
    host: redis-session.session-dev.svc.cluster.local
    port: 6379
---
spring:
  profiles: prd
  application:
    name: session-spring-prd
  redis:
    host: redis-session.session-prd.svc.cluster.local
    port: 6379